// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPaths(arg1:Array<string>):Promise<Array<main.QueueItem>>;

export function AnswerQuestion(arg1:number,arg2:string):Promise<void>;

export function CancelShutdown():Promise<main.ShutdownState>;

export function DeleteProfile(arg1:string):Promise<Array<main.Profile>>;

export function DownloadConverter(arg1:boolean):Promise<main.DownloadResult>;

export function GetConfigView():Promise<main.ConfigView>;

export function GetConverterStatus():Promise<main.ConverterStatus>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetQueueStatus():Promise<main.QueueState>;

export function GetSRTCleaner():Promise<main.SRTCleanerView>;

export function GetSavings():Promise<main.SavingsReport>;

export function GetSettingsFile():Promise<main.SettingsFile>;

export function GetStartupInfo():Promise<main.StartupInfo>;

export function GetTheme():Promise<string>;

export function HideProgress():Promise<void>;

export function IsRunning():Promise<boolean>;

export function NeedsSetup():Promise<boolean>;

export function PickFiles():Promise<Array<main.QueueItem>>;

export function PickFolder():Promise<Array<main.QueueItem>>;

export function PickJoinFiles():Promise<Array<main.JoinFile>>;

export function PickWatchFolder():Promise<string>;

export function ResetSavings():Promise<main.SavingsReport>;

export function RunSetup():Promise<void>;

export function SaveProfile(arg1:main.Profile):Promise<Array<main.Profile>>;

export function SaveSRTCleaner(arg1:Array<main.SRTPhrase>):Promise<main.SaveResult>;

export function SaveSettings(arg1:Record<string, string>):Promise<main.SaveResult>;

export function SaveTheme(arg1:string):Promise<void>;

export function SetShutdownWhenDone(arg1:boolean):Promise<main.ShutdownState>;

export function ShowBusy():Promise<void>;

export function ShowProgress(arg1:number):Promise<void>;

export function ShutdownStatus():Promise<main.ShutdownState>;

export function SignalDone():Promise<void>;

export function SortJoinFiles(arg1:Array<string>):Promise<Array<main.JoinFile>>;

export function StartRun(arg1:main.RunRequest):Promise<void>;

export function StartWatching(arg1:string):Promise<main.WatchState>;

export function StopArea(arg1:string):Promise<void>;

export function StopSlot(arg1:number):Promise<void>;

export function StopWatching():Promise<main.WatchState>;

export function WatchStatus():Promise<main.WatchState>;
