// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DownloadConverter(arg1) {
  return window['go']['main']['App']['DownloadConverter'](arg1);
}

export function GetConfigView() {
  return window['go']['main']['App']['GetConfigView']();
}

export function GetConverterStatus() {
  return window['go']['main']['App']['GetConverterStatus']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetQueueStatus() {
  return window['go']['main']['App']['GetQueueStatus']();
}

export function GetSRTCleaner() {
  return window['go']['main']['App']['GetSRTCleaner']();
}

export function GetSavings() {
  return window['go']['main']['App']['GetSavings']();
}

export function GetSettingsFile() {
  return window['go']['main']['App']['GetSettingsFile']();
}

export function GetStartupInfo() {
  return window['go']['main']['App']['GetStartupInfo']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function HideProgress() {
  return window['go']['main']['App']['HideProgress']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function NeedsSetup() {
  return window['go']['main']['App']['NeedsSetup']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickJoinFiles() {
  return window['go']['main']['App']['PickJoinFiles']();
}

export function PickWatchFolder() {
  return window['go']['main']['App']['PickWatchFolder']();
}

export function ResetSavings() {
  return window['go']['main']['App']['ResetSavings']();
}

export function RunSetup() {
  return window['go']['main']['App']['RunSetup']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveSRTCleaner(arg1) {
  return window['go']['main']['App']['SaveSRTCleaner'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function ShowBusy() {
  return window['go']['main']['App']['ShowBusy']();
}

export function ShowProgress(arg1) {
  return window['go']['main']['App']['ShowProgress'](arg1);
}

export function SignalDone() {
  return window['go']['main']['App']['SignalDone']();
}

export function SortJoinFiles(arg1) {
  return window['go']['main']['App']['SortJoinFiles'](arg1);
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopArea(arg1) {
  return window['go']['main']['App']['StopArea'](arg1);
}

export function StopSlot(arg1) {
  return window['go']['main']['App']['StopSlot'](arg1);
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}

export function WatchStatus() {
  return window['go']['main']['App']['WatchStatus']();
}
