// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function AnswerQuestion(arg1) {
  return window['go']['main']['App']['AnswerQuestion'](arg1);
}

export function DownloadConverter(arg1) {
  return window['go']['main']['App']['DownloadConverter'](arg1);
}

export function GetConfigView() {
  return window['go']['main']['App']['GetConfigView']();
}

export function GetConverterStatus() {
  return window['go']['main']['App']['GetConverterStatus']();
}

export function GetSettingsFile() {
  return window['go']['main']['App']['GetSettingsFile']();
}

export function GetStartupInfo() {
  return window['go']['main']['App']['GetStartupInfo']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickJoinFiles() {
  return window['go']['main']['App']['PickJoinFiles']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SortJoinFiles(arg1) {
  return window['go']['main']['App']['SortJoinFiles'](arg1);
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function StopRun() {
  return window['go']['main']['App']['StopRun']();
}
